Web/Controllers/AdminController.cs
using Dominio.Entidades;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.IO;
using System.Net;
using Web.Models;
using System.Data.Linq;
using System.Drawing;

namespace Web.Controllers
{
    public class AdminController : Controller
    {
        private BaseDatos baseDatos = new BaseDatos(ConfigurationManager.ConnectionStrings["baseDatos"].ConnectionString);

        public bool checkSession()
        {
            return Session["ID"] == null;
        }

        public ActionResult Index()
        {
            if (checkSession()) return RedirectToRoute("login");
            ViewBag.Empresa = baseDatos.Usuarios.Where(u => u.Id == (int)Session["ID"]).SingleOrDefault().Nombre;
            return View(baseDatos.Productos.Where(producto => producto.Empresa == (int)Session["ID"]));
        }

        public ActionResult Editar(int ID)
        {
            if (checkSession()) return RedirectToRoute("login");
            Producto producto = baseDatos.Productos.FirstOrDefault(p => p.Id == ID);
            return View(producto);
        }

        public FileContentResult GetImage(int id)
        {
            Producto prod = baseDatos.Productos.FirstOrDefault(p => p.Id == id);
            if (prod != null && prod.imagenContenido != null) {
                return File(prod.imagenContenido, prod.imagenTipo);
            }
            else
            {                
                return File(System.IO.File.ReadAllBytes(Server.MapPath("~/Imagenes/default/sin_foto.png")), "image/png");
            }
        }

        [HttpPost]
        public ActionResult Editar(Producto producto, HttpPostedFileBase imagen = null)
        {

            if (ModelState.IsValid)
            {
                if (imagen != null)
                {
                    producto.imagenTipo = imagen.ContentType;
                    producto.imagenContenido = new byte[imagen.ContentLength];
                    imagen.InputStream.Read(producto.imagenContenido, 0, imagen.ContentLength);
                }

                if (producto.Id == 0)
                {
                    baseDatos.Productos.InsertOnSubmit(producto);
                }
                else
                {                    
                    Producto productoBD = baseDatos.Productos.FirstOrDefault(p => p.Id == producto.Id);
                    productoBD.imagenTipo = producto.imagenTipo;
                    productoBD.imagenContenido = producto.imagenContenido;
                    productoBD.Nombre = producto.Nombre;
                    productoBD.Descripcion = producto.Descripcion;
                    productoBD.Categoria = producto.Categoria;
                    productoBD.Precio = producto.Precio;
                }

                baseDatos.SubmitChanges();

                TempData["Mensaje"] = string.Format("{0} ha sido guardado", producto.Nombre);                
                return RedirectToAction("Index");
            }
            else
            {            
                return View(producto);
            }
        }

        public ActionResult Crear()
        {
            if (checkSession()) return RedirectToRoute("login");
            return View("Editar", new Producto());
        }

        [HttpPost]
        public ActionResult Borrar(int IDProducto)
        {
            Producto productoBorrar = baseDatos.Productos.FirstOrDefault(p => p.Id == IDProducto );

            if (productoBorrar != null) {
                baseDatos.Productos.DeleteOnSubmit(productoBorrar);
                baseDatos.SubmitChanges();
                TempData["Mensaje"] = string.Format("{0} borrado con exito", productoBorrar.Nombre);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Upload()
        {
            if (checkSession()) return RedirectToRoute("login");
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase[] files, string delimitador)
        {
            List<string> OK = new List<string>();
            List<string> KO = new List<string>();
            if (files[0] != null)
            {
                string filename = "";
                foreach (HttpPostedFileBase file in files)
                {
                    string filepathtosave = "";
                    try
                    {
                        filename = file.FileName;
                        filepathtosave = "~/Imagenes/" + filename;
                        file.SaveAs(Server.MapPath(filepathtosave));

                        string[] contenidoFile = System.IO.File.ReadAllLines(Server.MapPath("~/Imagenes/" + filename));

                        Dictionary<int, string> cabeceras = new Dictionary<int, string>();

                        string[] splitCabeceras = contenidoFile[0].Split(Convert.ToChar(delimitador));
                        int longSplit = splitCabeceras.Length;
                        string cabecera = "";
                        string[] cabecerasInteresantes = new string[] { "nombre", "descripcion", "precio", "categoria" };
                        for (int i = 0; i < longSplit; i++)
                        {
                            cabecera = splitCabeceras[i].ToLower();
                            if (cabecerasInteresantes.Contains(cabecera) && !cabeceras.ContainsValue(cabecera))
                            {
                                cabeceras[i] = cabecera;
                            }
                        }

                        string linea = "";
                        int longitud = contenidoFile.Length;
                        string[] splitLinea;
                        Producto producto;
                        string valor;
                        for (int i = 1; i < longitud; i++)
                        {
                            linea = contenidoFile[i];
                            producto = new Producto();
                            producto.Empresa = (int)Session["ID"];
                            splitLinea = linea.Split(Convert.ToChar(delimitador));
                            for (int j = 0; j < splitLinea.Length; j++)
                            {
                                valor = splitLinea[j];
                                if (cabeceras.ContainsKey(j))
                                {
                                    switch (cabeceras[j])
                                    {
                                        case "nombre":
                                            producto.Nombre = valor;
                                            break;
                                        case "descripcion":
                                            producto.Descripcion = valor;
                                            break;
                                        case "categoria":
                                            producto.Categoria = valor;
                                            break;
                                        case "precio":
                                            valor = valor.Replace(".", ",");
                                            producto.Precio = Convert.ToDecimal(valor);
                                            break;
                                    }
                                }
                            }
                            if (baseDatos.Productos.Where(p => p.Empresa == producto.Empresa && p.Nombre == producto.Nombre).SingleOrDefault() == null)
                            {
                                baseDatos.Productos.InsertOnSubmit(producto);
                            }
                        }
                        
                        OK.Add("Fichero " + file.FileName + " Subido correctamente");
                    }
                    catch
                    {
                        KO.Add("Error al subir el fichero " + file.FileName);
                    }

                    baseDatos.SubmitChanges();
                    System.IO.File.Delete(Server.MapPath(filepathtosave));
                }
            }
            ViewBag.OK = OK;
            ViewBag.KO = KO;            
            return View();
        }
    }
}

Web/Controllers/NavegadorController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Dominio.Entidades;
using System.Configuration;

namespace Web.Controllers
{
    public class NavegadorController : Controller
    {
        private BaseDatos baseDatos = new BaseDatos(ConfigurationManager.ConnectionStrings["baseDatos"].ConnectionString);

        public PartialViewResult Menu(string categoria = null)
        {

            ViewBag.categoriaSeleccionada = categoria;
            IEnumerable<string> modelo = baseDatos.Productos
                                    .Select(p => p.Categoria)
                                    .Distinct()
                                    .OrderBy(p => p);
            return PartialView(modelo);
        }
    }
}

Web/Controllers/ProductosController.cs
using System.Linq;
using System.Web.Mvc;
using Dominio.Entidades;
using System.Configuration;
using Web.Models;
using System.Web.Security;
using System.Collections.Generic;
using System;

namespace Web.Controllers
{
    public class ProductosController : Controller
    {
        private BaseDatos baseDatos = new BaseDatos(ConfigurationManager.ConnectionStrings["baseDatos"].ConnectionString);
        int MaxProductosPagina = 6;
        int MaxEmpresasPagina = 6;

        public bool checkSession()
        {
            return Session["ID"] == null;
        }

        public ActionResult Listar(string categoria, int pagina = 1)
        {         
            if (checkSession()) return RedirectToRoute("login");

            IEnumerable<Producto> productos = baseDatos.Productos
                    .Where(p => categoria == null || p.Categoria == categoria)
                    .Skip((pagina - 1) * MaxProductosPagina)
                    .Take(MaxProductosPagina);

            List<Producto> productosFiltrados = new List<Producto>();

            foreach(Producto prod in productos)
            {
                bool encontrado = false;
                foreach(Producto p in productosFiltrados)
                {
                    if(p.Nombre == prod.Nombre)
                    {
                        encontrado = true;
                    }                   
                }

                if (!encontrado)
                {
                    productosFiltrados.Add(prod);
                }
            }

            ListaProductosViewModel modelo = new ListaProductosViewModel
            {
                Productos = productosFiltrados.AsEnumerable(),

                InfoPagina = new InformacionPagina
                {
                    PaginaActual = pagina,
                    ProductosPagina = MaxProductosPagina,
                    ProductosTotales = categoria == null ? baseDatos.Productos.Count() : baseDatos.Productos.Where(p => p.Categoria == categoria).Count()
                },

                CategoriaActual = categoria
            };

            return View(modelo);
        }        

        public ActionResult SeleccionarEmpresa( string nombre, string UrlAnterior, int pagina = 1 )
        {
            if (checkSession()) return RedirectToRoute("login");

            Producto producto = baseDatos.Productos.FirstOrDefault(p => p.Nombre == nombre);

            ListaEmpresasViewModel modelo = new ListaEmpresasViewModel
            {
                Empresas = baseDatos.Usuarios
                    .Where(empresa => empresa.Productos.Where(p => p.Nombre == nombre).Count() > 0 )
                    .OrderBy(empresa => empresa.Id)
                    .Skip((pagina - 1) * MaxEmpresasPagina)
                    .Take(MaxEmpresasPagina),

                InfoPagina = new InformacionPagina
                {
                    PaginaActual = pagina,
                    ProductosPagina = MaxEmpresasPagina,
                    ProductosTotales = baseDatos.Usuarios.Select(e => e.Productos).Count()
                },

                Producto = producto
            };

            ViewBag.UrlAnterior = UrlAnterior;
            return View(modelo);
        }

        public ActionResult Pedidos(string año1, string año2, string mes1, string mes2, string estado = "activas" )
        {
            if (checkSession()) return RedirectToRoute("login");
            ViewBag.Busqueda = "Activas";
            IEnumerable<Pedido> pedidos = baseDatos.Pedidos.Where(pedido => pedido.Usuario == (int)Session["ID"]).OrderByDescending(p => p.Fecha_Insercion);
            switch (estado)
            {
                case "activas":
                    pedidos = pedidos.Where(p => p.Estado < 2);
                    ViewBag.Busqueda = "Activas";
                    break;
                case "espera":
                    pedidos = pedidos.Where(p => p.Estado == 0);
                    ViewBag.Busqueda = "En Espera";
                    break;
                case "curso":
                    pedidos = pedidos.Where(p => p.Estado == 1);
                    ViewBag.Busqueda = "En Curso";
                    break;
                case "terminadas":
                    pedidos = pedidos.Where(p => p.Estado == 2);
                    ViewBag.Busqueda = "Terminadas";
                    break;
                case "rechazadas":
                    pedidos = pedidos.Where(p => p.Estado == 3);
                    ViewBag.Busqueda = "Rechazadas";
                    break;
                default:
                    ViewBag.Busqueda = "Todas";
                    break;
            }

            DateTime fecha1;
            DateTime fecha2;

            if (año1 != null && año1 != "")
            {
                fecha1 = new DateTime(Convert.ToInt32(año1), 1, 1);
                if (año2 != null && año2 != "")
                {
                    fecha2 = new DateTime(Convert.ToInt32(año1), 1, 1);
                    pedidos = pedidos.Where(p => p.Fecha_Insercion > fecha1 && p.Fecha_Insercion < fecha2);
                }
                else
                {
                    pedidos = pedidos.Where(p => p.Fecha_Insercion > fecha1 && p.Fecha_Insercion < DateTime.Now);
                }
            }
            else
            {
                año1 = 2000.ToString();
            }

            if (mes1 != null && mes1 != "")
            {
                fecha1 = new DateTime(Convert.ToInt32(año1), Convert.ToInt32(mes1), 1);
                if (mes2 != null && mes2 != "")
                {
                    fecha2 = new DateTime(Convert.ToInt32(año1), Convert.ToInt32(mes2), 1);
                    pedidos = pedidos.Where(p => p.Fecha_Insercion > fecha1 && p.Fecha_Insercion < fecha2);
                }
                else
                {
                    pedidos = pedidos.Where(p => p.Fecha_Insercion > fecha1 && p.Fecha_Insercion < DateTime.Now);
                }
            }

            return View(pedidos);
        }

        public string Accion(int id, int accion)
        {
            Pedido pedido = baseDatos.Pedidos.Where(p => p.Id == id).SingleOrDefault();

            switch (accion)
            {
                case 0:
                    pedido.Estado += 1;
                    if (pedido.Estado == 2)
                    {
                        pedido.Fecha_Entregado = DateTime.Now;
                    }
                    break;
                case 1:
                    pedido.Estado = 3;
                    break;
                case 2:
                    baseDatos.Pedidos.DeleteOnSubmit(pedido);
                    break;
            }

            baseDatos.SubmitChanges();
            return "ok";
        }
    }
}

Web/Views/Shared/SumarioEmpresa.cshtml
@model Dominio.Entidades.Usuario

<div id="pop_@Model.Id">
    <img src="@Url.Action("GetImage", "Admin", new { id = Model.Id })" height="507" width="600" border="0">
</div>

<div class="well">
    @if (Model.imagenContenido != null)
    {
    <div class="pull-left" style="margin-right: 10px">
        <img class="img-thumbnail" id="@Model.Id" width="75" height="75" src="@Url.Action("GetImage", "Admin", new { id = Model.Id })" />
    </div>
    }
    else
    {
    <div class="pull-left" style="margin-right: 10px">
        <img class="img-thumbnail" id="@Model.Id" width="75" height="75" src="~/Imagenes/default/sin_foto.png" />
    </div>
    }
 

    <h3>
        <strong>@System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Model.Nombre)</strong>        
    </h3>


    @using (Html.BeginForm("AñadirAlCarro", "Carro"))
    {
        <div class="pull-right">
            @Html.Hidden("Nombre", Model.Nombre)
            @Html.Hidden("IDEmpresa", Model.Id)
            @Html.Hidden("UrlAnterior", "/")
            <input type="submit" class="btn btn-success" value="Añadir al carro" />
        </div>
    }
    <span class="lead text-info">Direccion - @Model.Direccions.Calle</span>
</div>


<style>
    #pop {
        z-index: 2;
        position: absolute;
        text-align: center;
        border: 1px solid lightgrey;
    }

    #cerrar {
        float: right;
        margin-right: 5px;
        cursor: pointer;
        font: Verdana, Arial, Helvetica, sans-serif;
        font-size: 12px;
        font-weight: bold;
        color: #FFFFFF;
        background-color: #666666;
        width: 12px;
        position: relative;
        margin-top: -1px;
        text-align: center;
    }
</style>

<script>

    $(document).ready(function () {

        //Recolocamos el div pop
        $("div[id^='pop']").detach().prependTo("#body");

        //Conseguir valores de la img
        var img_w = $("div[id^='pop'] img").width() + 10;
        var img_h = $("div[id^='pop'] img").height() + 28;

        //Darle el alto y ancho
        $("div[id^='pop']").css('width', img_w + 'px');
        $("div[id^='pop']").css('height', img_h + 'px');

        //Esconder el popup
        $("div[id^='pop']").hide();

        //Consigue valores de la ventana del navegador
        var w = $(this).width();
        var h = $(this).height();

        //Centra el popup
        w = (w / 2) - (img_w / 2);
        h = (h / 2) - (img_h / 2);
        $("div[id^='pop']").css("left", w + "px");
        $("div[id^='pop']").css("top", h + "px");

        $(".img-thumbnail").click(function () {
            $("#pop_" + $(this).prop("id")).slideDown();
        });

        //Función para cerrar el popup
        $("div[id^='pop']").click(function () {
            $(this).slideUp();
        });
    });
</script>

Web/Views/Shared/SumarioProducto.cshtml
@model Dominio.Entidades.Producto

<div id="pop_@Model.Id">
    <img src="@Url.Action("GetImage", "Admin", new { id = Model.Id })" height="507" width="600" border="0">
</div>

<div class="well">     
    @if (Model.imagenContenido != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" id="@Model.Id" width="75" height="75" src="@Url.Action("GetImage", "Admin", new { id = Model.Id })" />
        </div>
    }
    else
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" id="@Model.Id" width="75" height="75" src="~/Imagenes/default/sin_foto.png" />
        </div>
    }  

    <h3>
        <strong>@System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Model.Nombre)</strong>
        <span class="pull-right label label-success"> @Model.Precio.ToString("c") </span>
    </h3>
    
    @if (!Request.Url.LocalPath.Contains("SeleccionarEmpresa"))
    {
        using (Html.BeginForm("SeleccionarEmpresa", "Productos"))
        {
            <div class="pull-right">
                @Html.Hidden("nombre", Model.Nombre)
                @Html.Hidden("UrlAnterior", Request.Url.PathAndQuery)
            
                <input type="submit" class="btn btn-success" value="Seleccionar Empresa" />
            
            </div>
        }
    }
    <span class="lead">@Model.Descripcion</span>
</div>


<style>
    div[id^='pop'] {
        z-index: 2;
        position: absolute;
        text-align: center;
        border: 1px solid lightgrey;
        margin-top: 10px;
    }
</style>

<script>

    $(document).ready(function () {

        //Recolocamos el div pop
        $("div[id^='pop']").detach().prependTo("#body");

        //Conseguir valores de la img
        var img_w = $("div[id^='pop'] img").width() + 10;
        var img_h = $("div[id^='pop'] img").height() + 28;

        //Darle el alto y ancho
        $("div[id^='pop']").css('width', img_w + 'px');
        $("div[id^='pop']").css('height', img_h + 'px');

        //Esconder el popup
        $("div[id^='pop']").hide();

        //Consigue valores de la ventana del navegador
        var w = $(this).width();
        var h = $(this).height();

        //Centra el popup
        w = (w / 2) - (img_w / 2);
        h = (h / 2) - (img_h / 2);
        $("div[id^='pop']").css("left", w + "px");
        $("div[id^='pop']").css("top", h + "px");

        $(".img-thumbnail").click(function () {
            $("#pop_" + $(this).prop("id")).slideDown();
        });

        //Función para cerrar el popup
        $("div[id^='pop']").click(function () {
            $(this).slideUp();
        });
    });
</script>

Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Scripts/Stylo.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>HealthCare</title>
</head>
<body>
    <div class="alert alert-success" style="width: 100%; height: 60px; margin: 0"></div>
    <a href="/"><div class="jumbotron page-header" style="margin: 0"></div></a>
    <div class="alert alert-info" style="width:100%; height: 60px">
        <a class="btn btn-info" href="/Login/Desconectar">Desconectar</a>
        <a href="/Empresas/Pedidos" class="btn btn-success navbar-right">Ver Pedidos</a>
        <a class="btn btn-info navbar-right" href="/Login/EditarCuenta" style="margin-right: 20px">Editar Cuenta</a>
    </div>
    <div>
        @if (TempData["Mensaje"] != null)
        {
            <div class="alert alert-success">@TempData["Mensaje"]</div>
        }
    </div>
    <div class="container" id="body">
        @RenderBody()
    </div> 
    <div id="bottom" class="alert alert-success">
    </div>  
</body>
</html>


Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Scripts/Stylo.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>HealthCare</title>
</head>
<body>
    <div class="alert alert-success" style="width: 100%; height: 60px; margin: 0"></div>
    <a href="/"><div class="jumbotron page-header" style="margin: 0"></div></a>
    <div class="alert alert-info" style="width:100%; height: 60px">
        <a class="btn btn-info" href="/Login/Desconectar">Desconectar</a>
        @Html.Action("Sumario", "Carro")
        <a class="btn btn-info navbar-right" href="/Login/EditarCuenta" style="margin-right: 20px">Editar Cuenta</a>
        @if (Request.Url.AbsolutePath.Contains("Pedidos"))
        {
            <a class="btn btn-info navbar-right" href="/Productos/Listar" style="margin-right: 20px">Ver Productos</a>
        }
        else
        {
            <a class="btn btn-info navbar-right" href="/Productos/Pedidos" style="margin-right: 20px">Historial Pedidos</a>
        }
        
    </div>

    <div class="row" id="body">
        @if (Request.Url.AbsolutePath.Contains("Listar"))
        {
            <div id="categorias" class="col-xs-2">
                @Html.Action("Menu", "Navegador")
            </div>
        }
        else
        {
            <div id="categorias" class="col-xs-2"></div>
        }
        <div class="col-xs-9">
            @RenderBody()
        </div>

            </div>
    <div id="bottom" class="alert alert-success"></div>
    
</body>
</html>

Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Scripts/Stylo.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 
    <title>HealthCare</title>
</head>
<body> 
    <div class="alert alert-success" style="width: 100%; height: 60px; margin: 0;"></div>
    <a href="/"><div class="jumbotron page-header" style="margin: 0"></div></a>
    <div class="alert alert-info" style="width:100%; height: 60px">
        @if (Request.Url.AbsolutePath.Contains("Login"))
        {
            <a href="/Login/Recuperar" class="btn btn-success navbar-right">Recuperar Contraseña</a>
        }
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <div id="bottom" class="alert alert-success"></div>
</body>
</html>

Web/Views/Shared/_PedidosLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <link href="~/Scripts/Stylo.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>HealthCare</title>
</head>
<body>
    <div class="alert alert-success" style="width: 100%; height: 60px; margin: 0"></div>
    <a href="/"><div class="jumbotron page-header" style="margin: 0"></div></a>
    <div class="alert alert-info" style="width:100%; height: 60px">
        <a class="btn btn-info" href="/Login/Desconectar">Desconectar</a>
        <a href="/Admin/Index" class="btn btn-success navbar-right">Gestionar Productos</a>
        <a class="btn btn-info navbar-right" href="/Login/EditarCuenta" style="margin-right: 20px">Editar Cuenta</a>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <div id="bottom" class="alert alert-success"></div>
</body>
</html>